upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 900
memory_limit = 512M

session.cookie_httponly = 1
session.cookie_samesite = Lax
session.use_strict_mode = 1

redis.session.locking_enabled = 1
