<?php

return [
    'GET' => [
        '/' => ['controller' => 'VideoController', 'action' => 'homepage'],
        '/watch' => ['controller' => 'VideoController', 'action' => 'watch'],
        '/login' => ['controller' => 'AuthController', 'action' => 'loginForm'],
        '/register' => ['controller' => 'AuthController', 'action' => 'registerForm'],
        '/search' => ['controller' => 'VideoController', 'action' => 'search'],
        '/upload' => ['controller' => 'VideoController', 'action' => 'uploadForm'],
        '/logout' => ['controller' => 'AuthController', 'action' => 'logout'],
        '/settings' => ['controller' => 'SettingsController', 'action' => 'index'],
        '/verify' => ['controller' => 'AuthController', 'action' => 'verify'],
        '/channel' => ['controller' => 'ChannelController', 'action' => 'index'],
        '/forgot'        => ['controller' => 'AuthController', 'action' => 'forgotForm'],
        '/reset'         => ['controller' => 'AuthController', 'action' => 'resetForm'],
        '/subscriptions' => ['controller' => 'FeedController', 'action' => 'subscriptions'],
        '/history'       => ['controller' => 'FeedController', 'action' => 'history'],
        '/liked'         => ['controller' => 'FeedController', 'action' => 'liked'],
        '/shorts'        => ['controller' => 'FeedController', 'action' => 'shorts'],
        '/tag' => ['controller' => 'VideoController', 'action' => 'tag'],
        '/watch-later' => ['controller' => 'FeedController', 'action' => 'watchLater'],
        '/notifications' => ['controller' => 'NotificationController', 'action' => 'index'],
        '/video/edit' => ['controller' => 'VideoController', 'action' => 'editForm'],
        '/playlists'  => ['controller' => 'PlaylistController', 'action' => 'index'],
        '/playlist'   => ['controller' => 'PlaylistController', 'action' => 'show'],
        '/studio'     => ['controller' => 'StudioController', 'action' => 'index'],
        '/notifications/count', ['controler' => 'NotificationController', 'action' => 'count'],
    ],
    'POST' => [
        '/login' => ['controller' => 'AuthController', 'action' => 'login'],
        '/register' => ['controller' => 'AuthController', 'action' => 'register'],
        '/upload' => ['controller' => 'VideoController', 'action' => 'upload'],
        '/like/toggle' => ['controller' => 'LikeController','action' => 'toggle'],
        '/sub/toggle' => ['controller' => 'SubController','action' => 'toggle'],
        '/settings' => ['controller' => 'SettingsController', 'action' => 'update'],
        '/comment/store'  => ['controller' => 'CommentController', 'action' => 'store'],
        '/comment/delete' => ['controller' => 'CommentController', 'action' => 'delete'],
        '/comment/pin'    => ['controller' => 'CommentController', 'action' => 'pin'],
        '/comment/like'   => ['controller' => 'CommentController', 'action' => 'like'],
        '/comment/edit' => ['controller' => 'CommentController', 'action' => 'edit'],
        '/forgot'        => ['controller' => 'AuthController', 'action' => 'forgot'],
        '/reset'         => ['controller' => 'AuthController', 'action' => 'reset'],
        '/account/delete'=> ['controller' => 'SettingsController', 'action' => 'deleteAccount'],
        '/history' => ['controller' => 'FeedController', 'action' => 'history'],
        '/tag' => ['controller' => 'VideoController', 'action' => 'tag'],
        '/watch-later/toggle' => ['controller' => 'FeedController', 'action' => 'toggleWatchLater'],
        '/notifications/read' => ['controller' => 'NotificationController', 'action' => 'markRead'],
        '/video/delete' => ['controller' => 'VideoController', 'action' => 'delete'],
        '/video/edit' => ['controller' => 'VideoController', 'action' => 'edit'],
        '/playlist/create'       => ['controller' => 'PlaylistController', 'action' => 'create'],
        '/playlist/add-video'    => ['controller' => 'PlaylistController', 'action' => 'addVideo'],
        '/playlist/remove-video' => ['controller' => 'PlaylistController', 'action' => 'removeVideo'],
        '/playlist/delete'       => ['controller' => 'PlaylistController', 'action' => 'delete'],
        '/studio/quick-edit'     => ['controller' => 'StudioController', 'action' => 'quickEdit'],
    ]
];
